# Generated by Django 3.0.8 on 2020-08-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='fligths',
            new_name='flights',
        ),
    ]
